# -*- coding: utf-8 -*-
"""Contenuti delle pagine pubbliche "cosa fare a Juan-les-Pins", 4 lingue."""

SLUG = {
    "it": "cosa-fare-juan-les-pins",
    "en": "en/things-to-do-juan-les-pins",
    "fr": "fr/que-faire-juan-les-pins",
    "de": "de/juan-les-pins-tipps",
}

GUIDE = {
"it": {
  "meta_title": "Cosa fare a Juan-les-Pins e Antibes: spiagge, ristoranti, escursioni",
  "meta_desc": "Guida a Juan-les-Pins e Antibes: le migliori spiagge, il centro storico, il Museo Picasso, Jazz à Juan, dove mangiare e come muoversi sulla Costa Azzurra.",
  "back": "Torna al sito",
  "kicker": "Guida alla zona",
  "h1": "Cosa fare a <em>Juan-les-Pins</em> e Antibes",
  "intro": "Juan-les-Pins è una delle località più amate della Costa Azzurra: sabbia fine, pinete, un lungomare vivace la sera e un festival jazz che dal 1960 porta qui i più grandi musicisti del mondo. Insieme ad Antibes, di cui fa parte, forma un piccolo territorio dove si concentrano spiagge, storia, mercati provenzali e sentieri sul mare. Questa guida raccoglie i posti che consigliamo agli ospiti di La Terrasse Bleue, con le distanze reali dall'appartamento.",
  "s1_t": "Le spiagge",
  "s1_p": "La costa qui cambia carattere ogni pochi minuti a piedi: sabbia fine e stabilimenti attrezzati a Juan-les-Pins, calette più tranquille verso il Cap d'Antibes.",
  "beaches": [
    ("Plage du Centre", "2 minuti a piedi", "La spiaggia principale di Juan-les-Pins, sabbia fine e acqua bassa nei primi metri: la più comoda con bambini. Alterna tratti liberi e stabilimenti con lettini e ristorante."),
    ("Port Gallice", "8 minuti a piedi", "Meno affollata anche in alta stagione, accanto al porto turistico. Buona per una nuotata veloce nel tardo pomeriggio."),
    ("Plage du Ponteil", "15 minuti", "Ampia spiaggia di Antibes riparata dal vento, con prato alberato alle spalle: comoda per passare l'intera giornata."),
    ("Plage de la Salis", "20 minuti", "Una delle più belle della zona, con vista sui bastioni della vecchia Antibes e sul Fort Carré."),
    ("Plage de la Garoupe", "25 minuti", "Sul Cap d'Antibes, acque trasparenti e riparate. Convivono spiaggia pubblica e beach club esclusivi; si raggiunge anche a piedi dal sentiero costiero."),
  ],
  "s2_t": "Antibes e il Cap",
  "s2_items": [
    ("Il centro storico di Antibes", "Vicoli medievali, botteghe e il <strong>Marché Provençal</strong> di Cours Masséna, aperto quasi ogni mattina: formaggi, olive, fiori, socca. Il modo migliore per iniziare la giornata."),
    ("Museo Picasso", "Ospitato nel Château Grimaldi affacciato sul mare, dove Picasso lavorò nel 1946. Una collezione piccola ma intensa, in uno degli edifici più belli della Costa Azzurra."),
    ("Sentier du Littoral", "Il sentiero che gira intorno al Cap d'Antibes tra scogli, ville nascoste e insenature: circa due ore di cammino con scorci che valgono da soli il viaggio. Scarpe chiuse consigliate."),
    ("Port Vauban e Fort Carré", "Uno dei porti più grandi del Mediterraneo, con la fortezza cinquecentesca che lo domina dall'alto. Bello al tramonto."),
  ],
  "s3_t": "Jazz à Juan",
  "s3_p": "Ogni luglio la <strong>Pinède Gould</strong>, a pochi minuti dall'appartamento, ospita il festival Jazz à Juan: dal 1960 ci sono passati Ray Charles, Miles Davis, Ella Fitzgerald. Nelle stesse settimane la città si riempie di concerti gratuiti, mercatini serali e locali aperti fino a tardi. Se pensate di venire in quel periodo, conviene prenotare con largo anticipo.",
  "s4_t": "Gite in giornata",
  "trips": [
    ("Cannes", "15 minuti in treno", "La Croisette, il Palais des Festivals, le boutique e il mercato Forville. Da qui partono i battelli per le Îles de Lérins."),
    ("Nizza", "30 minuti in treno", "Promenade des Anglais, la città vecchia, il mercato dei fiori di Cours Saleya e il museo Matisse a Cimiez."),
    ("Îles de Lérins", "mezza giornata", "Sainte-Marguerite e Saint-Honorat: pinete, acqua trasparente, l'abbazia dei monaci e la cella dove fu rinchiusa la Maschera di Ferro."),
    ("Saint-Paul-de-Vence", "40 minuti in auto", "Borgo fortificato di gallerie d'arte e vicoli in pietra, con la Fondation Maeght poco fuori le mura."),
    ("Grasse", "45 minuti in auto", "La capitale mondiale del profumo: visite alle storiche maison e laboratori dove si compone la propria fragranza."),
  ],
  "s5_t": "Dove mangiare",
  "s5_p": "Qualche indirizzo che consigliamo abitualmente, dal pranzo veloce alla cena importante. Nei mesi estivi è quasi sempre necessario prenotare.",
  "food": [
    ("La Passagère", "Cucina gastronomica, cena speciale"),
    ("L'Escale", "Pesce e frutti di mare fronte mare"),
    ("Le Ruban Bleu", "Classico di Juan-les-Pins, cucina di mare"),
    ("L'Institution", "Bistrot contemporaneo, atmosfera vivace"),
    ("Terre et Mer", "Cucina provenzale, buon rapporto qualità-prezzo"),
    ("Le Bistrot Juan-les-Pins", "Piatti semplici, comodo per il pranzo"),
  ],
  "s6_t": "Come muoversi",
  "s6_items": [
    ("A piedi", "Spiaggia, ristoranti, negozi e stazione sono tutti entro dieci-quindici minuti dall'appartamento: per la vita quotidiana l'auto non serve."),
    ("In treno", "La stazione di Juan-les-Pins è sulla linea costiera: Antibes a una fermata, Cannes a 15 minuti, Nizza a 30. È il modo più semplice per le gite in giornata, senza problemi di parcheggio."),
    ("In aereo", "L'aeroporto di Nizza Costa Azzurra dista circa 25-30 minuti in auto, con collegamenti in bus e treno."),
    ("In auto", "Utile per l'entroterra (Grasse, Saint-Paul-de-Vence, i borghi). L'appartamento include un posto auto privato coperto, un vantaggio concreto in estate, quando parcheggiare in centro diventa difficile."),
  ],
  "cta_t": "Il vostro punto di partenza",
  "cta_p": "La Terrasse Bleue è un appartamento con terrazza privata a due minuti dalla spiaggia di Juan-les-Pins: due camere, fino a quattro ospiti, parcheggio coperto incluso.",
  "cta_btn": "Scopri l'appartamento",
},

"en": {
  "meta_title": "Things to do in Juan-les-Pins and Antibes: beaches, restaurants, day trips",
  "meta_desc": "A guide to Juan-les-Pins and Antibes: the best beaches, the old town, the Picasso Museum, Jazz à Juan, where to eat and how to get around the French Riviera.",
  "back": "Back to the site",
  "kicker": "Area guide",
  "h1": "Things to do in <em>Juan-les-Pins</em> and Antibes",
  "intro": "Juan-les-Pins is one of the most loved spots on the French Riviera: fine sand, pine groves, a seafront that comes alive after dark, and a jazz festival that has been bringing the world's greatest musicians here since 1960. Together with Antibes, of which it is part, it forms a small area packed with beaches, history, Provençal markets and coastal paths. This guide gathers the places we recommend to guests of La Terrasse Bleue, with real distances from the apartment.",
  "s1_t": "The beaches",
  "s1_p": "The coast changes character every few minutes on foot: fine sand and well-equipped beach clubs in Juan-les-Pins, quieter coves towards Cap d'Antibes.",
  "beaches": [
    ("Plage du Centre", "2 minutes on foot", "The main beach of Juan-les-Pins: fine sand and shallow water at the shoreline, the easiest option with children. A mix of free stretches and clubs with sunbeds and a restaurant."),
    ("Port Gallice", "8 minutes on foot", "Quieter even in high season, right by the marina. Ideal for a quick late-afternoon swim."),
    ("Plage du Ponteil", "15 minutes", "A wide, wind-sheltered beach in Antibes with a shaded lawn behind it: good for a full day out."),
    ("Plage de la Salis", "20 minutes", "One of the finest around, looking towards the ramparts of old Antibes and the Fort Carré."),
    ("Plage de la Garoupe", "25 minutes", "On Cap d'Antibes, with clear, sheltered water. Public beach and exclusive beach clubs sit side by side; you can also walk there along the coastal path."),
  ],
  "s2_t": "Antibes and the Cap",
  "s2_items": [
    ("The old town of Antibes", "Medieval lanes, small shops and the <strong>Marché Provençal</strong> on Cours Masséna, open most mornings: cheese, olives, flowers, socca. The best way to start the day."),
    ("Picasso Museum", "Housed in the seafront Château Grimaldi, where Picasso worked in 1946. A small but intense collection in one of the most beautiful buildings on the Riviera."),
    ("Sentier du Littoral", "The path that loops around Cap d'Antibes between rocks, hidden villas and inlets: about two hours of walking, with views that are worth the trip on their own. Closed shoes recommended."),
    ("Port Vauban and Fort Carré", "One of the largest marinas in the Mediterranean, watched over by a 16th-century star fort. Best at sunset."),
  ],
  "s3_t": "Jazz à Juan",
  "s3_p": "Every July the <strong>Pinède Gould</strong>, a few minutes from the apartment, hosts the Jazz à Juan festival: since 1960 Ray Charles, Miles Davis and Ella Fitzgerald have all played here. During those weeks the town fills with free concerts, evening markets and venues open late. If you are thinking of coming then, book well in advance.",
  "s4_t": "Day trips",
  "trips": [
    ("Cannes", "15 minutes by train", "La Croisette, the Palais des Festivals, the boutiques and the Forville market. Boats to the Lérins Islands leave from here."),
    ("Nice", "30 minutes by train", "Promenade des Anglais, the old town, the flower market on Cours Saleya and the Matisse museum in Cimiez."),
    ("Lérins Islands", "half a day", "Sainte-Marguerite and Saint-Honorat: pine woods, clear water, the monks' abbey and the cell where the Man in the Iron Mask was held."),
    ("Saint-Paul-de-Vence", "40 minutes by car", "A fortified village of art galleries and stone lanes, with the Fondation Maeght just outside the walls."),
    ("Grasse", "45 minutes by car", "The world capital of perfume: tours of the historic houses and workshops where you can compose your own fragrance."),
  ],
  "s5_t": "Where to eat",
  "s5_p": "A few addresses we regularly recommend, from a quick lunch to a special dinner. In summer booking is almost always necessary.",
  "food": [
    ("La Passagère", "Fine dining, for a special evening"),
    ("L'Escale", "Fish and seafood on the waterfront"),
    ("Le Ruban Bleu", "A Juan-les-Pins classic, seafood cooking"),
    ("L'Institution", "Contemporary bistro, lively atmosphere"),
    ("Terre et Mer", "Provençal cooking, good value"),
    ("Le Bistrot Juan-les-Pins", "Simple dishes, handy for lunch"),
  ],
  "s6_t": "Getting around",
  "s6_items": [
    ("On foot", "Beach, restaurants, shops and the station are all within ten to fifteen minutes of the apartment: for daily life you do not need a car."),
    ("By train", "Juan-les-Pins station is on the coastal line: Antibes one stop away, Cannes 15 minutes, Nice 30. The easiest way to make day trips, with no parking worries."),
    ("By plane", "Nice Côte d'Azur airport is about 25-30 minutes away by car, with bus and train connections."),
    ("By car", "Useful for the hinterland (Grasse, Saint-Paul-de-Vence, the hill villages). The apartment includes a private covered parking space — a real advantage in summer, when parking in the centre becomes difficult."),
  ],
  "cta_t": "Your base on the Riviera",
  "cta_p": "La Terrasse Bleue is an apartment with a private terrace two minutes from the beach in Juan-les-Pins: two bedrooms, up to four guests, covered parking included.",
  "cta_btn": "See the apartment",
},

"fr": {
  "meta_title": "Que faire à Juan-les-Pins et Antibes : plages, restaurants, excursions",
  "meta_desc": "Guide de Juan-les-Pins et Antibes : les plus belles plages, la vieille ville, le musée Picasso, Jazz à Juan, où manger et comment se déplacer sur la Côte d'Azur.",
  "back": "Retour au site",
  "kicker": "Guide de la région",
  "h1": "Que faire à <em>Juan-les-Pins</em> et Antibes",
  "intro": "Juan-les-Pins est l'une des stations les plus appréciées de la Côte d'Azur : sable fin, pinèdes, un front de mer animé le soir et un festival de jazz qui, depuis 1960, y fait venir les plus grands musiciens du monde. Avec Antibes, dont elle fait partie, elle forme un petit territoire où se concentrent plages, histoire, marchés provençaux et sentiers au bord de l'eau. Ce guide rassemble les endroits que nous conseillons aux voyageurs de La Terrasse Bleue, avec les distances réelles depuis l'appartement.",
  "s1_t": "Les plages",
  "s1_p": "Le littoral change de caractère tous les quelques minutes à pied : sable fin et plages aménagées à Juan-les-Pins, criques plus tranquilles vers le Cap d'Antibes.",
  "beaches": [
    ("Plage du Centre", "2 minutes à pied", "La plage principale de Juan-les-Pins, sable fin et eau peu profonde sur les premiers mètres : la plus pratique avec des enfants. Alternance de zones libres et de plages privées avec transats et restaurant."),
    ("Port Gallice", "8 minutes à pied", "Moins fréquentée même en haute saison, à côté du port de plaisance. Parfaite pour une baignade en fin d'après-midi."),
    ("Plage du Ponteil", "15 minutes", "Grande plage d'Antibes abritée du vent, avec une pelouse ombragée à l'arrière : idéale pour la journée entière."),
    ("Plage de la Salis", "20 minutes", "L'une des plus belles du secteur, face aux remparts du vieil Antibes et au Fort Carré."),
    ("Plage de la Garoupe", "25 minutes", "Au Cap d'Antibes, eaux claires et abritées. Plage publique et clubs privés s'y côtoient ; on y accède aussi à pied par le sentier du littoral."),
  ],
  "s2_t": "Antibes et le Cap",
  "s2_items": [
    ("La vieille ville d'Antibes", "Ruelles médiévales, boutiques et le <strong>marché provençal</strong> du cours Masséna, ouvert presque tous les matins : fromages, olives, fleurs, socca. La meilleure façon de commencer la journée."),
    ("Musée Picasso", "Installé dans le château Grimaldi face à la mer, où Picasso travailla en 1946. Une collection petite mais forte, dans l'un des plus beaux bâtiments de la Côte d'Azur."),
    ("Sentier du Littoral", "Le sentier qui fait le tour du Cap d'Antibes entre rochers, villas cachées et criques : environ deux heures de marche, avec des points de vue qui justifient à eux seuls le détour. Chaussures fermées conseillées."),
    ("Port Vauban et Fort Carré", "L'un des plus grands ports de plaisance de Méditerranée, dominé par une forteresse du XVIe siècle. Superbe au coucher du soleil."),
  ],
  "s3_t": "Jazz à Juan",
  "s3_p": "Chaque mois de juillet, la <strong>Pinède Gould</strong>, à quelques minutes de l'appartement, accueille le festival Jazz à Juan : depuis 1960 y sont passés Ray Charles, Miles Davis, Ella Fitzgerald. Pendant ces semaines, la ville se remplit de concerts gratuits, de marchés nocturnes et d'établissements ouverts tard. Si vous envisagez de venir à cette période, réservez très à l'avance.",
  "s4_t": "Excursions à la journée",
  "trips": [
    ("Cannes", "15 minutes en train", "La Croisette, le Palais des Festivals, les boutiques et le marché Forville. Les bateaux pour les îles de Lérins partent d'ici."),
    ("Nice", "30 minutes en train", "Promenade des Anglais, le vieux Nice, le marché aux fleurs du cours Saleya et le musée Matisse à Cimiez."),
    ("Îles de Lérins", "une demi-journée", "Sainte-Marguerite et Saint-Honorat : pinèdes, eau transparente, l'abbaye des moines et la cellule du Masque de Fer."),
    ("Saint-Paul-de-Vence", "40 minutes en voiture", "Village fortifié de galeries d'art et de ruelles pavées, avec la Fondation Maeght juste en dehors des remparts."),
    ("Grasse", "45 minutes en voiture", "La capitale mondiale du parfum : visites des maisons historiques et ateliers pour composer sa propre fragrance."),
  ],
  "s5_t": "Où manger",
  "s5_p": "Quelques adresses que nous recommandons régulièrement, du déjeuner rapide au dîner d'exception. En été, la réservation est presque toujours indispensable.",
  "food": [
    ("La Passagère", "Cuisine gastronomique, pour un dîner d'exception"),
    ("L'Escale", "Poissons et fruits de mer face à la mer"),
    ("Le Ruban Bleu", "Un classique de Juan-les-Pins, cuisine de la mer"),
    ("L'Institution", "Bistrot contemporain, ambiance animée"),
    ("Terre et Mer", "Cuisine provençale, bon rapport qualité-prix"),
    ("Le Bistrot Juan-les-Pins", "Plats simples, pratique pour le déjeuner"),
  ],
  "s6_t": "Se déplacer",
  "s6_items": [
    ("À pied", "Plage, restaurants, commerces et gare sont tous à dix ou quinze minutes de l'appartement : au quotidien, la voiture est inutile."),
    ("En train", "La gare de Juan-les-Pins est sur la ligne littorale : Antibes à un arrêt, Cannes à 15 minutes, Nice à 30. Le moyen le plus simple pour les excursions, sans souci de stationnement."),
    ("En avion", "L'aéroport de Nice Côte d'Azur est à environ 25-30 minutes en voiture, avec liaisons en bus et en train."),
    ("En voiture", "Utile pour l'arrière-pays (Grasse, Saint-Paul-de-Vence, les villages perchés). L'appartement comprend une place de parking privée couverte, un vrai avantage en été, quand se garer au centre devient difficile."),
  ],
  "cta_t": "Votre point de départ",
  "cta_p": "La Terrasse Bleue est un appartement avec terrasse privée à deux minutes de la plage de Juan-les-Pins : deux chambres, jusqu'à quatre personnes, parking couvert inclus.",
  "cta_btn": "Découvrir l'appartement",
},

"de": {
  "meta_title": "Juan-les-Pins und Antibes: Strände, Restaurants, Ausflüge",
  "meta_desc": "Reiseführer für Juan-les-Pins und Antibes: die schönsten Strände, die Altstadt, das Picasso-Museum, Jazz à Juan, Restaurants und Verkehrsmittel an der Côte d'Azur.",
  "back": "Zurück zur Website",
  "kicker": "Umgebung",
  "h1": "Juan-les-Pins und Antibes <em>entdecken</em>",
  "intro": "Juan-les-Pins ist einer der beliebtesten Orte der Côte d'Azur: feiner Sand, Pinienhaine, eine abends lebendige Strandpromenade und ein Jazzfestival, das seit 1960 die größten Musiker der Welt hierherbringt. Zusammen mit Antibes, zu dem es gehört, bildet es ein kleines Gebiet voller Strände, Geschichte, provenzalischer Märkte und Küstenpfade. Dieser Leitfaden versammelt die Orte, die wir den Gästen von La Terrasse Bleue empfehlen, mit den tatsächlichen Entfernungen von der Wohnung.",
  "s1_t": "Die Strände",
  "s1_p": "Die Küste wechselt hier alle paar Gehminuten ihren Charakter: feiner Sand und gut ausgestattete Strandclubs in Juan-les-Pins, ruhigere Buchten Richtung Cap d'Antibes.",
  "beaches": [
    ("Plage du Centre", "2 Minuten zu Fuß", "Der Hauptstrand von Juan-les-Pins: feiner Sand und flaches Wasser am Ufer, mit Kindern am bequemsten. Freie Abschnitte wechseln sich mit Clubs mit Liegen und Restaurant ab."),
    ("Port Gallice", "8 Minuten zu Fuß", "Auch in der Hochsaison weniger voll, direkt am Yachthafen. Ideal für ein schnelles Bad am späten Nachmittag."),
    ("Plage du Ponteil", "15 Minuten", "Breiter, windgeschützter Strand in Antibes mit schattiger Wiese dahinter: gut für einen ganzen Tag."),
    ("Plage de la Salis", "20 Minuten", "Einer der schönsten der Gegend, mit Blick auf die Stadtmauern von Alt-Antibes und das Fort Carré."),
    ("Plage de la Garoupe", "25 Minuten", "Am Cap d'Antibes, klares und geschütztes Wasser. Öffentlicher Strand und exklusive Beachclubs liegen nebeneinander; erreichbar auch zu Fuß über den Küstenpfad."),
  ],
  "s2_t": "Antibes und das Cap",
  "s2_items": [
    ("Die Altstadt von Antibes", "Mittelalterliche Gassen, kleine Läden und der <strong>Marché Provençal</strong> am Cours Masséna, fast jeden Vormittag geöffnet: Käse, Oliven, Blumen, Socca. Der beste Start in den Tag."),
    ("Picasso-Museum", "Im Château Grimaldi direkt am Meer, wo Picasso 1946 arbeitete. Eine kleine, aber eindrucksvolle Sammlung in einem der schönsten Gebäude der Côte d'Azur."),
    ("Sentier du Littoral", "Der Pfad rund um das Cap d'Antibes zwischen Felsen, versteckten Villen und Buchten: etwa zwei Stunden Gehzeit, mit Ausblicken, die allein die Reise wert sind. Festes Schuhwerk empfohlen."),
    ("Port Vauban und Fort Carré", "Einer der größten Yachthäfen des Mittelmeers, überragt von einer Festung aus dem 16. Jahrhundert. Am schönsten bei Sonnenuntergang."),
  ],
  "s3_t": "Jazz à Juan",
  "s3_p": "Jeden Juli findet in der <strong>Pinède Gould</strong>, wenige Minuten von der Wohnung entfernt, das Festival Jazz à Juan statt: seit 1960 spielten hier Ray Charles, Miles Davis und Ella Fitzgerald. In diesen Wochen füllt sich der Ort mit Gratiskonzerten, Abendmärkten und lange geöffneten Lokalen. Wer in dieser Zeit kommen möchte, sollte früh buchen.",
  "s4_t": "Tagesausflüge",
  "trips": [
    ("Cannes", "15 Minuten mit dem Zug", "La Croisette, der Palais des Festivals, die Boutiquen und der Markt Forville. Von hier fahren die Boote zu den Lérins-Inseln."),
    ("Nizza", "30 Minuten mit dem Zug", "Promenade des Anglais, die Altstadt, der Blumenmarkt am Cours Saleya und das Matisse-Museum in Cimiez."),
    ("Lérins-Inseln", "ein halber Tag", "Sainte-Marguerite und Saint-Honorat: Pinienwälder, klares Wasser, die Abtei der Mönche und die Zelle des Mannes mit der eisernen Maske."),
    ("Saint-Paul-de-Vence", "40 Minuten mit dem Auto", "Befestigtes Dorf mit Kunstgalerien und Steingassen, die Fondation Maeght liegt kurz vor den Mauern."),
    ("Grasse", "45 Minuten mit dem Auto", "Die Welthauptstadt des Parfums: Führungen durch die historischen Häuser und Werkstätten, in denen man seinen eigenen Duft komponiert."),
  ],
  "s5_t": "Essen gehen",
  "s5_p": "Einige Adressen, die wir regelmäßig empfehlen, vom schnellen Mittagessen bis zum besonderen Abendessen. Im Sommer ist eine Reservierung fast immer nötig.",
  "food": [
    ("La Passagère", "Gehobene Küche, für einen besonderen Abend"),
    ("L'Escale", "Fisch und Meeresfrüchte direkt am Wasser"),
    ("Le Ruban Bleu", "Ein Klassiker in Juan-les-Pins, Fischküche"),
    ("L'Institution", "Zeitgenössisches Bistro, lebhafte Atmosphäre"),
    ("Terre et Mer", "Provenzalische Küche, gutes Preis-Leistungs-Verhältnis"),
    ("Le Bistrot Juan-les-Pins", "Einfache Gerichte, praktisch zum Mittagessen"),
  ],
  "s6_t": "Unterwegs",
  "s6_items": [
    ("Zu Fuß", "Strand, Restaurants, Geschäfte und Bahnhof liegen alle zehn bis fünfzehn Minuten von der Wohnung entfernt: für den Alltag braucht es kein Auto."),
    ("Mit dem Zug", "Der Bahnhof von Juan-les-Pins liegt an der Küstenlinie: Antibes eine Station, Cannes 15 Minuten, Nizza 30. Der einfachste Weg für Tagesausflüge, ohne Parkplatzsuche."),
    ("Mit dem Flugzeug", "Der Flughafen Nizza Côte d'Azur ist etwa 25-30 Autominuten entfernt, mit Bus- und Zugverbindungen."),
    ("Mit dem Auto", "Nützlich für das Hinterland (Grasse, Saint-Paul-de-Vence, die Bergdörfer). Zur Wohnung gehört ein privater überdachter Stellplatz — im Sommer ein echter Vorteil, wenn Parken im Zentrum schwierig wird."),
  ],
  "cta_t": "Ihr Ausgangspunkt",
  "cta_p": "La Terrasse Bleue ist eine Wohnung mit privater Terrasse, zwei Minuten vom Strand von Juan-les-Pins: zwei Schlafzimmer, bis zu vier Gäste, überdachter Parkplatz inklusive.",
  "cta_btn": "Die Wohnung ansehen",
},
}
